### PR TITLE
Get plugin compiling

### PR DESCRIPTION
**Pull request by Hevedy**
Remove duplicates.
Add support to read plugin files from project.

There still a problem at call the example from Discord:
https://discordapp.com/developers/docs/game-sdk/sdk-starter-guide

I get a < fatal error LNK1120: 1 unresolved externals> but can't figure right now with, if someone can find a solution for this...

### CODE REVIEW

**Comment by mastercoms** [comment]
Why were the includes removed?

**Comment by Hevedy** [comment]
> Why were the includes removed?

Mainly because you guys had the whole libs and includes duplicated:
Here: https://github.com/ProjectBorealis/DiscordGameSDK/tree/master/Source/ThirdParty/DiscordGameSDKLibrary
And here:
https://github.com/ProjectBorealis/DiscordGameSDK/tree/master/Source/ThirdParty

**Comment by mastercoms** [comment]
Haha, I don't know how I managed that one, thanks.

**Review by mastercoms — APPROVED** [review]

**Comment by mastercoms** [comment]
Thank you so much for your contribution to Project Borealis! We really appreciate it. Just so you know, we're [always hiring](https://www.projectborealis.com/#join)!

**Pull request merged**
